# Generated by Django 4.1.7 on 2023-04-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='facilitator',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
